# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "658395f255613d86c0892e7317451797"
application_url = "https://fireplace-organize-nervous-background.trycloudflare.com"
embedded = true
name = "remix-app"
handle = "remix-app-234"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fireplace-organize-nervous-background.trycloudflare.com/auth/callback",
  "https://fireplace-organize-nervous-background.trycloudflare.com/auth/shopify/callback",
  "https://fireplace-organize-nervous-background.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "kings-dev.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
